build:
  image: ensime/ensime:v2.x-cache
  pull: true
  environment:
    - JVM_OPTS=-XX:MaxPermSize=256m -Xss2m -Xms500m -Xmx500m
  commands:
    - git log | head -n 20 ;
    - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
    - cask pkg-file ;
      cask install ;
      cask package ;
    - cask exec ert-runner ;
    - cask exec ecukes ;
    - test/run_emacs_tests.sh || test/run_emacs_tests.sh ;
      if [ -n "$UNDERCOVER" ] && [ -f "coveralls.json" ] ; then
        curl -v -include --form json_file=@coveralls.json https://coveralls.io/api/v1/jobs || true ;
      fi
