;;; early-init.el -- Run at the beginning of Emacs startup sequence.

;;; Commentary:

;; This file was generated by org-babel from config.org and should not be edited
;; directly.

;;; Code:


(setq package-enable-at-startup nil)


(setq gc-cons-threshold most-positive-fixnum)
(setq gc-cons-percentage 0.7)
