;;; early-init.el -- Run at the beginning of Emacs startup sequence.  -*- lexical-binding: t; buffer-read-only: t; -*-

;;; Commentary:

;; This file was generated by org-babel from config.org and should not be edited
;; directly.

;;; Code:


(setenv "INSIDE_EMACS" "true")


(setq read-process-output-max (* 1024 1024))


(setq user-emacs-directory (file-name-directory (or load-file-name (buffer-file-name))))


(setq package-enable-at-startup nil)


(setq gc-cons-threshold most-positive-fixnum)
(setq gc-cons-percentage 0.7)


(when (boundp 'comp-eln-load-path)
  (let ((cache-dir "~/.cache/emacs/eln-cache/"))
    (mkdir cache-dir t)
    (add-to-list 'comp-eln-load-path cache-dir)))


(setq frame-resize-pixelwise t)


(custom-set-variables '(menu-bar-mode nil)
                      '(tool-bar-mode . nil)
                      '(scroll-bar-mode nil))

(modify-all-frames-parameters '((vertical-scroll-bars)))


(setq frame-title-format "Emacs")


(when (equal system-type 'darwin)
  (setq ns-use-proxy-icon nil)
  (modify-all-frames-parameters '((ns-appearance . dark)
                                  (ns-transparent-titlebar . t))))


(setq source-directory (expand-file-name emacs-version (getenv "NIX_EMACS_SRC_DIR")))


(when (equal system-type 'darwin)
  (dolist (dir (split-string (getenv "NIX_EMACS_DARWIN_PATH_EXTRAS") ":"))
    (push dir exec-path))
  (setq exec-path (seq-uniq exec-path))

  (setenv "PATH" (string-join exec-path ":")))
