#+TITLE: Chris Barrett's Emacs Config

My personal Emacs configuration. Requires Emacs 25 or later.

I don't really suggest anyone else uses my config as-is, since it's a personal
thing. It's probably most useful for cribbing ideas. :)

* Motivation

- Since I use Emacs for work, editor stability is very important to me.
- After using Spacemacs for a while, I wanted to go back to a slimmer setup that
  is easier to hack on when I need to integrate packages
- I've declared Emacs bankruptcy a few times. I know how to write one of these
  things. ;)

* General principles

- I use Evil
- I've extracted the leader key functionality from Spacemacs, so that's pretty
  similar
- I've themed Emacs to remove most source code color highlighting.
  - I've expiremented with using heavier font weights for important tokens
    instead. It feels like I'm reading a latex paper ;)
  - There's a toggle between light and dark colour themes, under =SPC t t=.
- For control and package stability, I use git subtrees to manage deps.
  - I use the following helper commands to work with subtrees:
    - =cb-emacs-add-subtree=
    - =cb-emacs-update-subtree=
    - =cb-emacs-push-subtree=
  - The only tricky thing is I need to remember to download any necessary
    transitive deps.

* Project Layout

In contrast with Spacemacs, this config uses =use-package= pretty directly.

- =init.el= :: Emacs' entrypoint for loading the config
- =config/= :: lisp configuration files, loosely grouped by functionality
- =lisp/= :: vendored 3rd-party lisp code and lisp packages

I also put any sensitive config in a =personal-config.el= file, not in this repo.

* Trying It Out

Clone into =~/.emacs.d= and start Emacs.

The makefile needs to be run in order to generate files for org-mode.

* I want to use your config

No you don't!

There is a kernel of a good config in here though. The following parts make the
bones of a good config:

- =init.el=
- =lisp/use-package=
- =lisp/magit= (and its transitive deps)
- =config/cb-emacs.el=
- =config/cb-git/git-subtree.el=

From there, you add more subtrees using =cb-emacs-add-subtree=, configure those
packages in =init.el=, and build out your config from there. Extract your config
into files in =config/= once it gets unwieldy.

Have a skim over the other config files to get a sense of what's around. See
=config/cb-basic-settings.el= for general quality of life customisations for core
Emacs features.
