# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  prettier = nodeEnv.buildNodePackage {
    name = "prettier";
    packageName = "prettier";
    version = "2.0.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier/-/prettier-2.0.5.tgz";
      sha512 = "7PtVymN48hGcO4fGjybyBSIWDsLU4H4XlvOHfq91pz9kkGlonzwTfYkaIEwiRg/dAJF9YlbsduBAgtYLi+8cFg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier is an opinionated code formatter";
      homepage = https://prettier.io/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}